default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/development.sqlite3
  
test:
  <<: *default
  database: rails_hum_test

production:
  <<: *default
  url: "postgresql://db:<%= Rails.application.credentials.do[:db_password] %>@<%= ENV['DATABASE_URL'] %>:25060/db?sslmode=require"
  #url: 'postgresql://user@localhost'

